# http://travis-ci.org/RDFLib/sparqlwrapper

sudo: false

language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7-dev
    - pypy

before_install:
    - pip install --upgrade pip setuptools

install:
    - python setup.py sdist && pip install ./dist/*

before_script:
    - pip install rdflib-jsonld

script: ./tests.sh 
