# http://travis-ci.org/RDFLib/sparqlwrapper

sudo: false

branches:
    only:
        - master

language: python

python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - pypy

install:
    - python setup.py sdist && pip install ./dist/*

script: ./tests.sh 
